 ;PREVIOUS COMMENTS

(define (main))
(define (barrier)
    (define size 0)
    (define (set val)
        (set! size val)
        )
    (define (install)
        (println "Installing barrier on " (gettid))
        (lock)
        (set! size (- size 1))
        (unlock)
        )
    (define (remove)
        (cond
            ((= size 0) 
                (println "Barrier removed on " (gettid)))
            (else
                (sleep 1)
                (remove))
            )
        )
    this
    )

(define (run5)
    (define b (barrier))
    (define (runner)
        ((b 'install))
        ((b 'remove))
        )

    ((b 'set) 3)
    (define thread1 (thread (runner)))
    (sleep 2)
    (define thread2 (thread (runner)))
    (sleep 2)
    (define thread3 (thread (runner)))
    (tjoin thread1)
    (tjoin thread2)
    (tjoin thread3)
    )
  (run5)
