(define (main)
	(setPort (open (getElement ScamArgs 1) 'read))
	(define arg1 (readExpr))
	(define arg2 (readExpr))
	(println arg1 " plus " arg2 " is " (big+ arg1 arg2))
	(println arg1 " minus " arg2 " is " (big- arg1 arg2 ))
	(println arg1 " times " arg2 " is " (big* arg1 arg2))
	(println arg1 " divided by " arg2 " is " (big/ arg1 arg2))
)

(define old+ +)
(define old* *)
(define old- -)
(define old/ /)

(define (compare a b)
    (define (compare-iter a b)
        (cond
            ((null? b) 1)
            ((null? a) -1)
            ((equal? (car a) '-) (compare-iter (cdr a) b))
            ((equal? (car b) '-) (compare-iter a (cdr b)))
            ((equal? a b) 0)
            ((> (length a) (length b)) 1)
            ((< (length a) (length b)) -1)
            ((> (car a) (car b)) 1)
            ((< (car a) (car b)) -1)
            (else (compare-iter (cdr a) (cdr b)))
        )
    )
    (compare-iter a b)
)

(define (imsad a b)
    (if (< (length a) (length b))
        (imsad (append a '(0)) b)
        a
    )
)

(define (removeZeros input)
        (if (= 0 (car input))
            (removeZeros (cdr input))
            input
        )
)
 
(define (rbig* multiplicand multiplier)
    (define (outerloop multiplierList resultList)
        (define (innerloop num multiplicandList carry output)
            (if (null? multiplicandList)
                (if (< 0 carry)
                    (append output (list carry))
                    output
                )
                (innerloop num (cdr multiplicandList) (/ (+ (* num (car multiplicandList)) carry) 10) (append output (list (% (+ (* num (car multiplicandList)) carry) 10))))
            )
        )
        (if (not (null? multiplierList))
            (outerloop (cdr multiplierList) (append resultList (list (innerloop (car multiplierList) multiplicand 0 '()))))
            resultList
        )
    )
 
    (define (addZeros n inlist outlist)
        (define (zeroLoop n ls)
            (if (= n 0)
                ls
                (zeroLoop (- n 1) (cons 0 ls))
            )
        )
        (if (not (null? inlist))
            (addZeros (+ n 1) (cdr inlist) (append outlist (list (zeroLoop n (car inlist)))))
            outlist
        )
    )
   
    (define (adder inlist total)
        (if (not (null? inlist))
            (adder (cdr inlist) (reverse (rbig+ (car inlist) total)))
            total
        )
    )
    (reverse (adder (addZeros 0 (outerloop multiplier '()) '()) '(0)))
)
 
(define (rbig/ dividend divisor)
    (define (iterate dendList tempDend output)
        (define (modifyLists count remain)
            (if (equal? remain '(0))
                (iterate dendList '() (append output (list count)))
                (iterate (append remain dendList) '() (append output (list count)))
            )
        )
 
        (define (count ogNumber stopHere curTotal i)
            (if (> 1 (compare (big+ ogNumber curTotal) stopHere))
                (count ogNumber stopHere (big+ ogNumber curTotal) (+ i 1))
                (modifyLists i (big- stopHere curTotal))
            )
        )

        (if (and (= 1 (compare divisor dendList)) (null? tempDend))
            output
            (if (and (not (null? dendList)) (= 0 (car dendList)) (null? tempDend)) 
                (iterate (cdr dendList) tempDend (append output '(0)))
                (if (= 1 (compare divisor tempDend))
                    (iterate (cdr dendList) (append tempDend (list (car dendList))) output)
                    (count divisor tempDend '(0) 0)
                )   
            )
        )
    )
   
    (if (equal? divisor '(0))
        (throw 'DIVISION_BY_ZERO "zero divisor")
        (iterate dividend '() '())
    )
)

(define (rbig+ augend addend)
    (define (add augend addend carry output)
        (if (null? augend)
            (if (> carry 0)
                (cons 1 output)
                output
            )
            (if (> 10 (+ (car addend) (car augend) carry))
                (add (cdr augend) (cdr addend) 0 (cons (+ (car addend) (car augend) carry) output))
                (add (cdr augend) (cdr addend) 1 (cons (- (+ (car addend) (car augend) carry) 10) output))
            )
        )
    )
    (if (not (= (length augend) (length addend)))
        (rbig+ (imsad augend addend) (imsad addend augend))
        (add augend addend 0 '())
    )
)

(define (big+ augend addend)
    (if (and (equal? (car augend) '-) (equal? (car addend) '-))
        (cons '- (rbig+ (reverse (cdr augend)) (reverse (cdr addend))))
        (if (and (not (equal? (car augend) '-)) (not (equal? (car addend) '-)))
            (rbig+ (reverse augend)(reverse addend))
            (cond
                ((< 0 (compare augend addend))
                    (if (equal? (car augend) '-)
                        (cons '- (big- (cdr augend) addend))
                        (big- augend (cdr addend))
                    )
                )
                ((= 0 (compare augend addend)) '(0))
                (else
                    (big+ addend augend)
                )
            )
        )
    )
)

(define (rbig- subtrahend minuend)
    (define (subtract subtrahend minuend output)
        (if (or (null? subtrahend) (and (equal? subtrahend '(0)) (equal? minuend '(0))))
            (removeZeros output)
            (if (< (car subtrahend) (car minuend))
                (subtract (cons (+ (car subtrahend) 10) (cons (- (cadr subtrahend) 1) (cddr subtrahend))) minuend output)
                (subtract (cdr subtrahend) (cdr minuend) (cons (- (car subtrahend) (car minuend)) output))
            )
        )
    )
    (if (not (= (length subtrahend) (length minuend)))
        (rbig- (imsad subtrahend minuend) (imsad minuend subtrahend))
        (subtract subtrahend minuend '())
    )
)
 
(define (big- subtrahend minuend)
    (define (flipper x)
        (if (equal? (car x) '-)
            (cdr x)
            (cons '- x)
        )
    )
    (cond
        ((equal? subtrahend minuend) '(0))
        ((or (> 1 (compare subtrahend minuend)) (equal? (car subtrahend) '-) (equal? (car minuend) '-))
            (big+ subtrahend (flipper minuend))
        )
        (else
            (rbig- (reverse subtrahend) (reverse minuend))
        )
    )
)
 
(define (big* multiplicand multiplier)
    (if (or (equal? multiplicand '(0)) (equal? multiplier '(0)))
        '(0)
        (if (equal? (car multiplicand) '-)
            (if (equal? (car multiplicand) '-)
                (rbig* (reverse (cdr multiplicand)) (reverse (cdr multiplier)))
                (cons '- (rbig* (reverse (cdr multiplicand)) (reverse multiplier)))
            )
            (if (equal? (car multiplier) '-)
                (cons '- (rbig* (reverse multiplicand) (reverse (cdr multiplier))))
                (rbig* (reverse multiplicand) (reverse multiplier))
            )
        )
    )
)
 
(define (big/ dividend divisor)
    (if (= 1 (compare divisor dividend)) 
        '(0)
        (if (equal? (car dividend) '-)
            (if (equal? (car divisor) '-)
                (rbig/ (cdr dividend) (cdr divisor))
                (cons '- (rbig/ (cdr dividend) divisor))
            )
            (if (equal? (car divisor) '-)
                (cons '- (rbig/ dividend (cdr divisor)))
                (rbig/ dividend divisor)
            )
        )
    )
)
