default:
	javac -d bin -sourcepath src src/evaluator/Evaluator.java

clean:
	rm -f bin/*/*

error1:
	java -classpath bin parser.Parser error1.max

error1x:
	dpl error1.max

error2:
	java -classpath bin parser.Parser error2.max

error2x:
	dpl error2.max

error3:
	java -classpath bin parser.Parser error3.max

error3x:
	dpl error3.max

arrays:
	java -classpath bin parser.Parser array.max

arraysx:
	dpl array.max

conditionals:
	java -classpath bin parser.Parser conditionals.max

conditionalsx:
	dpl conditionals.max

recursion:
	java -classpath bin parser.Parser fibonacci.max

recursionx:
	dpl fibonacci.max

iteration:
	java -classpath bin parser.Parser iterator.max

iterationx:
	dpl iterator.max

functions:
	java -classpath bin parser.Parser functions.max

functionsx:
	dpl functions.max

dictionary:
	java -classpath bin parser.Parser dictionary.max

dictionaryx:
	dpl dictionary.max

problem:
	java -classpath bin parser.Parser rpnCalculator.max

problemx:
	dpl rpnCalculator.max
